#!/usr/bin/env python
# encoding: utf-8
"""
:Description:剑指Offer 21
:Author: 佳境Shmily
:Create Time: 2020/4/29 11:59
:File: Solution21
:Site: shmily-qjj.top

"""


class Solution:
    def jumpFloor(self, number):
        # write code here
        pass

if __name__ == '__main__':
    s = Solution()
